point_cloud_topic: "/camera/depth/color/points"
# point_cloud_topic: "/velodyne_points"

map_frame_id: "map"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "/ndt/PoseWithCovarianceStamped"
robot_pose_cache_size: 200
track_point_frame_id: "/camera_link"
sensor_frame_id: "/camera_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0

# point_cloud_topic (string, default: "/points")

# 距离测量话题的名称

# robot_pose_topic (string, default: "/robot_state/pose")

# 机器人姿势和协方差话题的名称

# base_frame_id (string, default: "/robot")

# The id of the robot base tf frame.

# map_frame_id (string, default: "/map")

# The id of the tf frame of the elevation map.

# track_point_frame_id (string, default: "/robot")

# The elevation map is moved along with the robot following a track point. This is the id of the tf frame in which the track point is defined.

# track_point_x, track_point_y, track_point_z (double, default: 0.0, 0.0, 0.0)

# The elevation map is moved along with the robot following a track point. This is the position of the track point in the track_point_frame_id.
